version: '3.8'

services:
  nginx-reverse-proxy-demo:
    image: nginx:latest
    container_name: nginx-reverse-proxy-demo
    depends_on: 
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    image: nginx-demo-frontend
    container_name: nginx-demo-frontend
    build: 
      context: ./frontend
    ports:
      - "8080:80"
    depends_on: 
      - backend
    restart: on-failure
  
  backend:
    image: nginx-demo-backend
    container_name: nginx-demo-backend
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    restart: on-failure

